# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build & Publish

on:
  workflow_dispatch:
  release:
    types: [created]
  

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Source
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        name: Install dependencies
      - run: npm run package
        name: Build Package
      - run: npm publish --access public
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTOMATION_TOKEN}}
